version: '3'
services:
  nginx:
    image: nginx:1.12
    container_name: vue-nginx
    ports:
      - 80:80
    volumes:
      - ./:/vue-sample/
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    container_name: vue-app
    build: ./docker/app
    volumes:
      - ./:/vue-sample/
      - ./docker/app/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db

  composer:
    container_name: vue-composer
    build: ./docker/composer
    volumes:
      - ./:/vue-sample/
    working_dir: /vue-sample/

  node:
    image: node:lts
    container_name: vue-node
    volumes:
      - .:/vue-sample/
    working_dir: /vue-sample/
    entrypoint: ["npm"]
    command: ["help"]

  db:
    image: mysql
    container_name: vue-sample-db
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'vue-sample'
    volumes:
      - vue-sample-db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  vue-sample-db:
    driver: local
